# base-image for python on any machine using a template variable
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:latest

# install package dependencies
RUN apt-get update
RUN pip install --upgrade pip

# Set our working directory
WORKDIR /usr/src/app

# Copy requirements.txt first for better cache on later pushes
COPY requirements.txt requirements.txt

# pip install python deps from requirements.txt on the resin.io build server                      
RUN READTHEDOCS=True pip install -r requirements.txt

# set the environment variables
#TWILIO_ACCOUNT_SID=AC97666081a865104c19f0c2266ce81e08
#TWILIO_AUTH_TOKEN=189ba47c0d92194d8afc0a2b4e08ca06
#DEST_NUM=+18135194665
#HOST_NUM=+13852260092

# Copy all files in our root to the working directory of the container
COPY . ./

EXPOSE 5152

# main.py will run when the container starts up on the device
# CMD ["python","-u","webstreaming.py", "--ip", "0.0.0.0", "--port", "8000", "--frame-count", "16"]
CMD ["python", "-u", "app.py"]