FROM grafana/grafana

WORKDIR /usr/src/app

COPY ./conf/datasources.yml /etc/grafana/provisioning/datasources/

COPY ./conf/dash* /etc/grafana/provisioning/dashboards/

# Apply custom config
RUN rm /etc/grafana/grafana.ini
COPY ./conf/grafana.ini /etc/grafana/

EXPOSE 3000

CMD [ "/usr/share/grafana/bin/grafana-server", "--homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --pac]