# base-image for python on any machine using a template variable
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:latest

# install package dependencies
RUN apt-get update
RUN apt-get install python-dev python-pip gcc
RUN pip install --upgrade pip

# Set our working directory
WORKDIR /usr/src/app

# Copy requirements.txt first for better cache on later pushes
COPY requirements.txt requirements.txt

# pip install python deps from requirements.txt on the resin.io build server                      
RUN pip install -r requirements.txt

# Copy all files in our root to the working directory of the container
COPY . ./

# Enable udevd so that plugged dynamic hardware devices show up in our container
ENV UDEV=1

# main.py will run when the container starts up on the device
CMD ["python","main.py"]