{
 "title": "Sensor Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature (F)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bme280_temperature_fahrenheit" }
   ]
  },
  {
   "title": "Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bme280_temperature_fahrenheit" }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bme280_relative_humidity" }
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bme280_relative_humidity" }
   ]
  },
  {
   "title": "Air Pressure (hPa)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bme280_pressure_hPa" }
   ]
  },
  {
   "title": "Air Pressure (hPa)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bme280_pressure_hPa" }
   ]
  },
  {
   "title": "Altitude (meters)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bme280_altitude_meters" }
   ]
  },
  {
   "title": "Altitude (m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bme280_altitude_meters" }
   ]
  }
 ]
}