{
 "title": "enviroPlus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oxidising",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"oxidising\" FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oxidising",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"oxidising\" FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reducing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"reducing\" FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reducing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"reducing\" FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NH3",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"nh3\" FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NH3",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"nh3\" FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Light (Lux)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"light\" FROM \"balena-sense\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Light (Lux)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 14, "x": 7, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"light\" FROM \"balena-sense\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
     "format": "humidity",
     "valueName": "current",
     "targets": [
      {
       "measurement": "balena-sense",
       "query": "SELECT \"humidity\" FROM \"balena-sense\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "humidity" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 14, "x": 7, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "%" }
     ],
     "targets": [
      {
       "measurement": "balena-sense",
       "query": "SELECT \"humidity\" FROM \"balena-sense\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "humidity" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
     "format": "celsius",
     "valueName": "current",
     "targets": [
      {
       "measurement": "balena-sense",
       "query": "SELECT \"temperature\" FROM \"balena-sense\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 5, "w": 14, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Temperature" }
     ],
     "targets": [
      {
       "measurement": "balena-sense",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
     "targets": [
      {
       "measurement": "balena-sense",
       "select": [
        [
         { "params": [ "pressure" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 14, "x": 7, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "mbar" }
     ],
     "targets": [
      {
       "measurement": "balena-sense",
       "select": [
        [
         { "params": [ "pressure" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}